Add a real ranch listener
How do I know how to do so? From the oficial ranch docs:
https://ninenines.eu/docs/en/ranch/2.0/guide/listeners/

And one more thing, `ranch:start_listener`, if successful, returns a
tuple `{ok, Listener}`, where `Listener` is some way to identify such
listener.

Note though, that in such call, one of the things we specify is a
callback module, that we named here basic_protocol, which doesn't exist
yet. What problems will this cause?

Let's run `rebar3 shell`, when you do so, you see that nothing happens,
everything seems to run fine. But when, from a different shell, we run
`telnet localhost 5555`, telnet errors, and we can see on the rebar3
shell a message like
```
error: Ranch listener the_listener connection process start failure; echo_protocol:start_link/3 crashed with reason: error:undef
```

Ah, another `undef`! Let's define this basic_protocol :)